version: 1.0.{build}
nuget:
  project_feed: true
install:
  choco install nuget.commandline
before_build:
  - nuget restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
test_script:
  - echo Tests disabled presently
deploy:
- provider: NuGet
  api_key:
    secure: Z1DoV4FAaop88LOqNhOuUf+SUrJtH2toXU5Kx++tXpJLAYWluu4ppfdbF+SUT+7+
  on:
    branch: master